models/Settlement.py
from main import db




class Settlement(db.Model):
    __tablename__ = "settlements"
    
    id = db.Column(db.Integer, primary_key=True)
    #settlement_s_tracks_count = db.Column(db.Integer())
    #settlement_s_users_count = db.Column(db.Integer())
    user_id = db.Column(db.Integer, db.ForeignKey("users.id"), nullable=True)

    name = db.Column(db.String())
    settdate = db.Column(db.String())
    address = db.Column(db.String())
    saleprice = db.Column(db.String())
    deposit = db.Column(db.String())
    ratesamount = db.Column(db.String())
    ratesstatus = db.Column(db.String())
    
    balance = db.Column(db.String())
    ratesdayspaid = db.Column(db.Integer())
    ratesdaysunpaid = db.Column(db.Integer())
    ratesoverpaid = db.Column(db.String())
    ratesunderpaid = db.Column(db.String())

    totalbalance = db.Column(db.String())

    
    # def __repr__(self):
    #     return f"<Track {self.settlement_title}>"

controllers/auth_controller.py
from models.User import User
from schemas.UserSchema import user_schema, users_schema
from main import db
from flask import Blueprint, request, jsonify, abort, render_template, redirect, url_for
from main import bcrypt

# from flask_jwt_extended import create_access_token
from flask_login import login_user, current_user, logout_user, login_required
from datetime import timedelta
auth = Blueprint('auth', __name__,)

@auth.route("/", methods=["GET"])
def main_page():
    return redirect(url_for('auth.signup'))

@auth.route("/auth/register", methods=["POST"])
def auth_register():
    username = request.form.get('username')
    password = request.form.get('password')
    print(username)
    print(password)

    #user_fields = user_schema.load(request.json)

    #avoid to create a user that already exists
    #user = User.query.filter_by(username=user_fields["username"]).first()
    user = User.query.filter_by(username=username).first()
    if user:
        return abort(400, description="user already exists")
    user = User()
    #user.username = user_fields["username"]
    #user.password = bcrypt.generate_password_hash(user_fields["password"]).decode("utf-8")
    user.username = username
    user.password = bcrypt.generate_password_hash(password).decode("utf-8")

    db.session.add(user)
    db.session.commit()

    #return jsonify(user_schema.dump(user))
    return redirect(url_for('auth.login'))

@auth.route("/auth/login", methods=["POST"])
def auth_login():
    username = request.form.get('username')
    #email = request.form.get('email')
    password = request.form.get('password')
    # print(username)
    # print(password)
    # user_fields = user_schema.load(request.json)

    
    # user = User.query.filter_by(username=user_fields["username"]).first()
    user = User.query.filter_by(username=username).first()

    # don't login if the user doesn't exist
    if not user: 
        return abort(401, description="Incorrect username")
        

    if not bcrypt.check_password_hash(user.password, password):
        return abort(401, description="Incorrect password")
    
    #print(current_user.username)
    login_user(user)
    #print(current_user.username)

    #expiry = timedelta(days=1)
    #access_token = create_access_token(identity=str(user.id), expires_delta=expiry)
    #return jsonify({"token": access_token})

    return redirect(url_for('settlements.settlement_index'))

@auth.route('/signup', methods=['GET'])
def signup():
    return render_template('signup.html')

@auth.route('/login', methods=['GET'])
def login():
    return render_template('login.html')

@auth.route('/logout', methods=['GET'])
@login_required
def logout():
    logout_user()
    return redirect(url_for('auth.login'))


@auth.route("/users", methods=["GET"])
def users_index():
     users = User.query.all()
     return jsonify(users_schema.dump(users))

controllers/settlements_controller.py
from models.User import User
from models.Settlement import Settlement

from schemas.UserSchema import user_schema, users_schema
from schemas.SettlementSchema import settlement_schema, settlements_schema

from main import db
from flask import Blueprint, request, jsonify, abort, render_template, redirect, url_for
from flask_jwt_extended import jwt_required, get_jwt_identity
from sqlalchemy.orm import joinedload
from flask_login import login_required, current_user

import sys
import datetime

settlements = Blueprint('settlements', __name__, url_prefix="/settlements")

@settlements.route("/newsettlement", methods=["GET"])
def newsettlement():
    return render_template("newsettlement.html")



@settlements.route("/", methods=["GET"])
def settlement_index():
    #Retrieve all settlements
    settlements = Settlement.query.all()
    return render_template("settlements_index.html", settlements=settlements)


@settlements.route("/", methods=["POST"])
@login_required
def settlement_create():
    
    # Create a new settlement
    name = request.form.get("name")
    settdate = datetime.datetime.date(datetime.datetime.strptime(request.form.get("settdate"),'%Y-%m-%d'))
    address = request.form.get("address")
    saleprice = float(request.form.get("saleprice"))
    deposit = float(request.form.get("deposit"))
    ratesamount = float(request.form.get("ratesamount"))
    ratesstatus = request.form.get("ratesstatus")

    #create a new Settlement object, with the data received in the request
    new_settlement = Settlement()
    new_settlement.name = name
    new_settlement.settdate = settdate
    
    new_settlement.address = address
    new_settlement.user_id = current_user.id

    new_settlement.saleprice = "{:.2f}".format(saleprice)
    new_settlement.deposit = "{:.2f}".format(deposit)
    new_settlement.ratesamount = "{:.2f}".format(ratesamount)
    new_settlement.ratesstatus = ratesstatus

    #calculations for fields
    balance = float((request.form.get("saleprice")))-float((request.form.get("deposit")))
    
    startrates = datetime.date(2020,7,1)
    endrates = datetime.date(2021,6,30)
    ratesdaystotal = endrates-startrates

    ratesdayspaid = endrates-settdate
    ratesdaysunpaid = settdate-startrates

    rdp = ratesdayspaid.days
    rdu = ratesdaysunpaid.days

    ratespaidfloat = float(ratesdayspaid.days)
    ratesdaystotalfloat = float(ratesdaystotal.days)

    ratesoverpaidrate = (ratespaidfloat / ratesdaystotalfloat)
    ratesunderpaidrate = (ratesdaysunpaid.days / ratesdaystotal.days)
    
    ratesoverpaid = (ratesoverpaidrate * ratesamount)
    ratesunderpaid = (ratesunderpaidrate * ratesamount)

    


    #Calculated fields from above
    if ratesstatus == "on":
        new_settlement.ratesoverpaid = "{:.2f}".format(ratesoverpaid)
        new_settlement.ratesdayspaid = rdp
        new_settlement.ratesunderpaid = "{:.2f}".format(0)
        new_settlement.ratesdaysunpaid = 0
        totalbalance = (balance+ratesoverpaid)

    else:
        new_settlement.ratesunderpaid = "{:.2f}".format(ratesunderpaid)
        new_settlement.ratesdaysunpaid = rdu
        new_settlement.ratesoverpaid = "{:.2f}".format(0)
        new_settlement.ratesdayspaid = 0
        totalbalance = (balance-ratesunderpaid)

    
    new_settlement.balance = "{:.2f}".format(balance)
    new_settlement.totalbalance = "{:.2f}".format(totalbalance)

    #add a new Settlement to the db
    db.session.add(new_settlement)
    db.session.commit()

    #return jsonify(settlement_schema.dump(new_settlement))
    return redirect(url_for('settlements.settlement_index'))




@settlements.route("/<int:id>", methods=["GET"])
#@jwt_required
def settlement_show(id):
    #Return a single settlement
    settlement = Settlement.query.get(id)
    #return jsonify(settlement_schema.dump(settlement))
    return render_template("settlements.html", settlement = settlement )



@settlements.route("/update/<int:id>", methods=["POST"])
@login_required
def settlement_update(id):
    #make sure the selected settlement is owned by the logged in user
    settlement = Settlement.query.filter_by(id=id, user_id=current_user.id).first()
    if not settlement:
        return abort(400, description="Not authorized to delete other people's settlements")

    # Create a new settlement
    name = request.form.get("name")
    settdate = datetime.datetime.date(datetime.datetime.strptime(request.form.get("settdate"),'%Y-%m-%d'))
    address = request.form.get("address")
    saleprice = float(request.form.get("saleprice"))
    deposit = float(request.form.get("deposit"))
    ratesamount = float(request.form.get("ratesamount"))
    ratesstatus = request.form.get("ratesstatus")

    #create a new Settlement object, with the data received in the request
    new_settlement = settlement
    new_settlement.name = name
    new_settlement.settdate = settdate
    
    new_settlement.address = address
    new_settlement.user_id = current_user.id

    new_settlement.saleprice = "{:.2f}".format(saleprice)
    new_settlement.deposit = "{:.2f}".format(deposit)
    new_settlement.ratesamount = "{:.2f}".format(ratesamount)
    new_settlement.ratesstatus = ratesstatus

    #calculations for fields
    balance = float((request.form.get("saleprice")))-float((request.form.get("deposit")))
    
    startrates = datetime.date(2020,7,1)
    endrates = datetime.date(2021,6,30)
    ratesdaystotal = endrates-startrates

    ratesdayspaid = endrates-settdate
    ratesdaysunpaid = settdate-startrates

    rdp = ratesdayspaid.days
    rdu = ratesdaysunpaid.days

    ratespaidfloat = float(ratesdayspaid.days)
    ratesdaystotalfloat = float(ratesdaystotal.days)

    ratesoverpaidrate = (ratespaidfloat / ratesdaystotalfloat)
    ratesunderpaidrate = (ratesdaysunpaid.days / ratesdaystotal.days)
    
    ratesoverpaid = (ratesoverpaidrate * ratesamount)
    ratesunderpaid = (ratesunderpaidrate * ratesamount)

    


    #Calculated fields from above
    if ratesstatus == "on":
        new_settlement.ratesoverpaid = "{:.2f}".format(ratesoverpaid)
        new_settlement.ratesdayspaid = rdp
        new_settlement.ratesunderpaid = "{:.2f}".format(0)
        new_settlement.ratesdaysunpaid = 0
        totalbalance = (balance+ratesoverpaid)

    else:
        new_settlement.ratesunderpaid = "{:.2f}".format(ratesunderpaid)
        new_settlement.ratesdaysunpaid = rdu
        new_settlement.ratesoverpaid = "{:.2f}".format(0)
        new_settlement.ratesdayspaid = 0
        totalbalance = (balance-ratesunderpaid)

    
    new_settlement.balance = "{:.2f}".format(balance)
    new_settlement.totalbalance = "{:.2f}".format(totalbalance)

    #save the changes
    db.session.commit()
    return redirect(url_for('settlements.settlement_index'))


@settlements.route("/delete/<int:id>", methods=["GET"])
@login_required
def settlement_delete(id):
    settlement = Settlement.query.filter_by(id=id, user_id=current_user.id).first()
    if not settlement:
        return abort(400, description="Not authorized to delete other people's settlements")

    db.session.delete(settlement)
    db.session.commit()
    
    return redirect(url_for('settlements.settlement_index'))



@settlements.route("/modify/<int:id>", methods=["GET"])
def modify_settlement(id):
    settlement = Settlement.query.get(id)
    return render_template("modify_settlement.html", settlement=settlement)

templates/layout copy.html
<!doctype html>
<html>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <head>
        <title> Simple Conveyancer </title>
    </head>

    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="#">Navbar</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="/settlements/">Settlements <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="/albums/">Albums</a>
            </li>
          </ul>
          <form class="form-inline my-2 my-lg-0">
            <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
          </form>
        </div>
      </nav>


    <body>
        <div class="container">
        {% block content %}

        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
        {% endblock %}
        </div>
    </body>
</html>

templates/layout.html
<!doctype html>
<html>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <head>
        <title> Simple Conveyancer </title>
    </head>

    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="#">Simple Conveyancer</a>
        
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>

        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">

          {% if current_user.is_authenticated  %}
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="/settlements/">My Settlements <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="/settlements/newsettlement">New Settlement</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{{ url_for('auth.logout') }}">Log Out</a>
            </li>
          </ul>

          {% else %}
          {% endif %}
        </div>
      </nav>


    <body>
        <div class="container">
        {% block content %}
        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
        
        {% endblock %}
        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
        
      </div>
        
    </body>
</html>

templates/login.html
{% extends "layout.html" %}

{% block content %}
    <div>
        <h3>Log in</h3>
        
        
        <div>
            <form action="{{ url_for('auth.auth_login') }}" method="POST">
                <input type="text" name="username" placeholder="Username" autofocus="">
                <input type="password" name="password" placeholder="Password">
                <button>Log in</button>
            </form>
        </div>
        <h5>-</h5>
        <h5>Not a registered user?</h5>
        <a href="signup"><button>Cancel / Go back to Sign Up</button></a>
    </div>
{% endblock %}

templates/modify_settlement.html
{% extends "layout.html" %}

{% block content %}
<style>
.row {
  white-space: nowrap;
  padding: 10px;
  width: 500px;
  margin: 20;
  justify-content: space-between;
}
</style>

    <div>
        <h3>Create New Settlement - BCC Rates Calculator</h3>
        <div>
            <form action="{{ url_for('settlements.settlement_update', id=settlement.id) }}" method="POST">
                <div class="row">
                    <h5>Client Name</h5><input type="text" name="name" value="{{ settlement.name }}" placeholder="" autofocus="">
                </div>

                <div class="row">
                    <h5>Settlement Date</h5><input type="date" name="settdate" value="{{ settlement.settdate }}" placeholder="" autofocus="">
                </div>

                <div class="row">
                    <h5>Property Address</h5><input type="text" name="address" value="{{ settlement.address }}" placeholder="" autofocus="">
                </div>

                <div class="row">
                    <h5>Sale Price</h5><input type="number" name="saleprice" value="{{ settlement.saleprice }}" placeholder="" autofocus="">
                </div>

                <div class="row">
                    <h5>Deposit</h5><input type="number" name="deposit" value="{{ settlement.deposit }}" placeholder="" autofocus="">
                </div>

                <div class="row">
                    <h5>BCC Rates Amount</h5><input type="number" name="ratesamount" value="{{ settlement.ratesamount }}" placeholder="" autofocus="">
                </div>

                <div class="row">
                    <h5>Rates Paid y/n?</h5><input type="checkbox" name="ratesstatus" value="{{ settlement.ratesstatus }}" placeholder="" autofocus="">
                </div>

                <button>Submit Data</button>
            </form>

        </div>
    </div>
{% endblock %}

templates/newsettlement.html
{% extends "layout.html" %}

{% block content %}
<style>
.row {
  white-space: nowrap;
  padding: 10px;
  width: 500px;
  margin: 20;
  justify-content: space-between;
}
</style>

    <div>
        <h3>Create New Settlement - BCC Rates Calculator</h3>
        <div>
            <form action="{{ url_for('settlements.settlement_create') }}" method="POST">
                <div class="row">
                    <h5>Client Name</h5><input type="text" name="name" placeholder="" autofocus="">
                </div>

                <div class="row">
                    <h5>Settlement Date</h5><input type="date" name="settdate" placeholder="" autofocus="">
                </div>

                <div class="row">
                    <h5>Property Address</h5><input type="text" name="address" placeholder="" autofocus="">
                </div>

                <div class="row">
                    <h5>Sale Price</h5><input type="number" name="saleprice" placeholder="" autofocus="">
                </div>

                <div class="row">
                    <h5>Deposit</h5><input type="number" name="deposit" placeholder="" autofocus="">
                </div>

                <div class="row">
                    <h5>BCC Rates Amount</h5><input type="number" name="ratesamount" placeholder="" autofocus="">
                </div>

                <div class="row">
                    <h5>Rates Paid y/n?</h5><input type="checkbox" name="ratesstatus" placeholder="" autofocus="">
                </div>

                <button>Submit Data</button>
            </form>

        </div>
    </div>
{% endblock %}

templates/settlements.html
{% extends "layout.html" %}

{% block content%}
<style>
    .row {
      white-space: nowrap;
      padding: 10px;
      width: 200px;
      margin: 20;
      justify-content: space-between;
    }
</style>

    {% if current_user.is_authenticated and current_user.id == settlement.user.id %}
    <div>
    <h6>Settlement ID: {{settlement.id}}</h6>
    <h6>Client Name: {{settlement.name}}</h6>
    <h6>Settlement Date: {{settlement.settdate}}</h6>
    <h6>_</h6>
    <h6><b>BCC Rates</b></h6>
    <h6>The current rates period is from 1 July 2020 to 30 June 2021.</h6>
    <h6>Total Brisbane City Council Rates: $ {{settlement.ratesamount}}</h6>
    <h6>_</h6>
    <h6><b>Days and period adjustment</b></h6>
    <h6>Rates Paid days Remaining in Period (Paid): {{settlement.ratesdayspaid}}</h6>
    <h6>Unpaid days from period start (Unpaid): {{settlement.ratesdaysunpaid}}</h6>
    <h6>_</h6>

    <h6>Sale Price: $ {{settlement.saleprice}}</h6>
    <h6>LESS Deposit: $ {{settlement.deposit}}</h6>
    <h6><u>Subtotal: $ {{settlement.balance}}</u></h6>
    <h6>_</h6>
    <h6>PLUS Rates Amount Overpaid: $ {{settlement.ratesoverpaid}}</h6>
    <h6>MINUS Rates Amount Underpaid: $ {{settlement.ratesunderpaid}}</h6>
    <h6>________</h6>
    <h6><b><u>TOTAL to be received at Settlement: $ {{settlement.totalbalance}}</u></b></h6>
    <h6>________</h6>


    </div>
    <a href="/settlements"><button>Go Back</button></a>
    <a href="{{ url_for('settlements.modify_settlement', id=settlement.id) }}"><button>Update Settlement</button></a>
    <a href="{{ url_for('settlements.settlement_delete', id=settlement.id) }}"><button>Delete Settlement</button></a>
    {% endif%}
    
{% endblock %}

templates/settlements_index.html
{% extends "layout.html" %}

{% block content%} 
<style>
.row {
  white-space: nowrap;
  padding: 10px;
  width: 500px;
  margin: 20;
  justify-content: space-between;
}
</style>


<h3>My Settlements</h3>          
    {% for settlement in settlements %}
        {% if current_user.is_authenticated and current_user.id == settlement.user_id %}
            
            <h5>Settlement ID: {{settlement.id}}</h5>
            <h5>Client Name: {{settlement.name}}</h5>
            <h5>Settlement Date: {{settlement.settdate}}</h5>
            <a href="{{ url_for('settlements.settlement_show', id=settlement.id) }}">Show Settlement Calculations</a>
            <h5>____</h5>
        {% endif%}

    {% endfor %}
{% endblock %}

templates/signup.html
{% extends "layout.html" %}

{% block content %}
    <div>
        <h3>Sign up</h3>
        <div>
            <form action="{{ url_for('auth.auth_register') }}" method="POST">
                <input type="text" name="username" placeholder="Username" autofocus="">
                <input type="password" name="password" placeholder="Password">
                <button>Sign up</button>
            </form>
        </div>
        <h5>-</h5>
        <h5>Already a registered User?</h5>
        <a href="login"><button>Go to Login</button></a>
    </div>
{% endblock %}